---
name: Complete Autonomous Research System
on:
  workflow_dispatch:

env:
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

jobs:
  autonomous-research-complete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Step 1 - Clone Methodology
        run: nix-shell -p git --run 'git clone https://github.com/garmir/claude-methodology.git ~/.claude'
      - name: Step 2 - Execute Claude Research
        run: |
          cd ~ && nix-shell -p nodejs expect --run 'expect -c "
            set timeout 300
            spawn npx @anthropic-ai/claude-code --dangerously-skip-permissions \"Using .claude methodology patterns: research network optimization tools and create summary\"
            expect { -re {.*style.*} { send \"1\r\" } }
            expect { -re {.*bypass.*} { send \"2\r\" } }
            expect { -re {.*research.*|.*summary.*|.*Write.*} { exit 0 } timeout { exit 1 } }
          "'
      - name: Step 3 - Create Research File
        run: nix-shell -p coreutils --run 'echo "Autonomous research with .claude methodology completed" > research-complete.txt'
      - name: Upload Complete Results
        uses: actions/upload-artifact@v4
        with:
          name: autonomous-research-complete
          path: research-complete.txt